### ISSUE TITLE
View Finals Location

### ISSUE THREAD

**Issue by vvp002** [vvp002/campus-mobile#13]
**User Story:**
As a student, I want to be able to view where my finals are being held so that I know where to go to attend them.

**Comment by slmnliu** [comment]
**Scenario:**
**_Given_** the user is logged in
_And_ the user is a student
_And_ the user is currently enrolled in classes

**_When_** the Finals Schedule Card appears

**_Then_** ensure the Finals Schedule Card displays the locations of Finals

**Comment by slmnliu** [comment]
Issue is **complete** as the Finals Card displays locations for finals.
