### ISSUE TITLE
Class Schedule Card Styling

### ISSUE THREAD

**Issue by vvp002** [vvp002/campus-mobile#14]
Fix the current styling for the class schedule card to match the mockup. Also must be able to handle dynamic text in Accessibility settings.

**Comment by namespacestd0** [comment]
Class Schedule Card Prototype
V2: https://xd.adobe.com/view/b317da4f-64e2-48d9-834c-ad2dc8fd21a9/
V3: https://xd.adobe.com/view/1b318cb3-9522-4032-a0b4-fe0c2c699e37/

**Comment by namespacestd0** [comment]
![course schedule ui documentation](https://user-images.githubusercontent.com/25359322/36756869-1850a4b4-1bc5-11e8-8846-9c512c450a32.png)

**Comment by slmnliu** [comment]
**Class Schedule Card View:**
<img width="375" alt="screen shot 2018-03-18 at 1 11 22 am" src="https://user-images.githubusercontent.com/16200637/37643703-a8ba8a0a-2bde-11e8-954b-856c93400788.png">

**Comment by vvp002** [comment]
**Current Class Schedule Card View:**
![screen shot 2018-03-20 at 9 08 17 am](https://user-images.githubusercontent.com/13816146/37667041-48f65b68-2c1e-11e8-8436-52065cbac793.png)

**Comment by vvp002** [comment]
-Had to replace the icons from Material Design with icons from vector-icons since they were displaying as boxes on some devices

**Comment by vvp002** [comment]
The issue is **complete** because the Class Schedule Card and the Finals Card is formatted/styled correctly according to the mockup.
