### ISSUE TITLE
View Finals Schedule Card

### ISSUE THREAD

**Issue by vvp002** [vvp002/campus-mobile#15]
**User Story:**
As a student, I want to be able to see my finals schedule on a card so I can easily know when they are and
 start preparing for them.

**Comment by slmnliu** [comment]
**Scenario:**
**_Given_** the user is logged in
_And_ the user is a student
_And_ the user is currently enrolled in classes
_And_ the user has Finals within a week (i.e. it is currently week 10)

**_When_** the Home View appears

**_Then_** ensure the Finals Schedule Card appears at the top of the Home View
_And_ ensure the Finals Schedule Card is displaying the user's upcoming Finals in chronological order

**Comment by slmnliu** [comment]
Time functionality for this issue (the appearance of this card only when it is near Finals' week, i.e. week 10) has been partitioned into a separate issue: "Add Time-Based Functionality to Finals Schedule Card"

**Comment by vvp002** [comment]
Finals Schedule Card is able to be viewed. All issues in Epic are closed and completed. Closing epic/issue
