### ISSUE TITLE
View Class Schedule Card

### ISSUE THREAD

**Issue by vvp002** [vvp002/campus-mobile#16]
**User Story:** 
As a student, I want to see my class schedule on a card so that I can easily know what classes I'm taking.

**Comment by slmnliu** [comment]
**Scenario:**
**_Given_** the user is logged in
_And_ the user is a student
_And_ the user is currently enrolled in classes

**_When_** the Home View appears

**_Then_** ensure the Class Schedule Card appears
_And_ ensure the Class Schedule Card is displaying the user's next four upcoming classes
_And_ ensure there is a button on the card that allows the user to go to the Full Schedule View

**Comment by slmnliu** [comment]
Time functionality for this issue (upcoming four classes appearing on the card) has been partitioned into a separate issue: "Add Time-Based Functionality to Class Schedule Card"

**Comment by slmnliu** [comment]
**Current Class Schedule Card:**
<img width="375" alt="screen shot 2018-03-18 at 1 11 22 am" src="https://user-images.githubusercontent.com/16200637/37644431-09735708-2be1-11e8-99b4-c04e47eeef3f.png">

**Comment by vvp002** [comment]
Class Schedule is able to be viewed. All issues in Epic are completed.
