### ISSUE TITLE
View Daily Class Schedule

### ISSUE THREAD

**Issue by vvp002** [vvp002/campus-mobile#2]
**User Story:**
As a student, I want to be able to see when my classes are for the day so that I know my schedule for the day.

**Comment by vvp002** [comment]
Scenario:
**_Given_** the user is logged in
_And_ the user is a student
_And_ the user is currently enrolled in classes

**_When_** the Home View appears

**_Then_** ensure the Class Schedule Card is displaying the user's courses that day
_And_ ensure the Class Schedule Card is displaying the correct times for those courses

**Comment by vvp002** [comment]
Changed layout of card to make it non-scrollable and made it more closely match Jerry's mock up. Need to fix the styling still.

**Comment by slmnliu** [comment]
The issue is **complete** because when the app is loaded and the user is on the Home View, the Class Schedule Card displays the user's courses with the correct times.
