### ISSUE TITLE
View Full Class Schedule

### ISSUE THREAD

**Issue by vvp002** [vvp002/campus-mobile#3]
**User Story:**
As a student, I want to view my full class schedule so that I can plan out my week accordingly.

**Comment by slmnliu** [comment]
**Scenario:** 
**Given** the user is logged in
_And_ the user is a student
_And_ the user is currently enrolled in classes

**When** the user presses a "View Full Schedule" button

**Then** ensure that the app displays the full class schedule screen with all the student's classes

**Comment by slmnliu** [comment]
The issue is **complete** as the app displays the Full Class Schedule view when the button is pressed in the Class Schedule card.
