### ISSUE TITLE
View Class Location

### ISSUE THREAD

**Issue by slmnliu** [vvp002/campus-mobile#7]
**User Story:**
As a student, I want to be able to view where my classes are being held so that I know where to go to attend them.

**Comment by vvp002** [comment]
Create function that links the icons in the Class Schedule and Finals Card so that it takes the user to the map view with a pin to the location of their class/final.

**Comment by slmnliu** [comment]
**Scenario:**
**_Given_** the user is logged in
_And_ the user is a student
_And_ the user is currently enrolled in classes

**_When_** the Class Schedule Card appears

**_Then_** ensure the Class Schedule Card displays locations for classes

**Comment by slmnliu** [comment]
Issue is **complete** because Class Schedule Card displays locations for classes.
