### ISSUE TITLE
View Class Professor 

### ISSUE THREAD

**Issue by slmnliu** [vvp002/campus-mobile#8]
**User Story:**
As a student, I want to be able to view what professor is teaching my class so that I know more about what to expect for my class.

**Comment by vvp002** [comment]
Able to pull class professor from static test data. Chose not to display it in the card and emphasize class, time, and location instead

**Comment by slmnliu** [comment]
**Scenario:**
**_Given_** the user is logged in
_And_ the user is a student
_And_ the user is currently enrolled in classes

**_When_** the Class Schedule Card appears

**_Then_** ensure the Class Schedule Card displays the professor for classes

**Comment by slmnliu** [comment]
Issue is **complete** as Class Schedule Card displays the professor for classes.
